apiVersion: v1
kind: Service
metadata:
  name: event-bus
spec:
  type: NodePort
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 3003
      targetPort: 3003
