apiVersion: v1
kind: Service
metadata:
  name: event-srv
spec:
  type: NodePort
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31515
