apiVersion: v1
kind: Service
metadata:
  name: post-srv
spec:
  type: NodePort
  selector:
    app: post-service
  ports:
    - name: post-service
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31515
